AuthSystem/urls.py
from django.urls import path
from . import views

app_name = 'AuthSystem'

urlpatterns = [
    path('', views.loginPage, name='loginPage'),
    path('signup/', views.signupPage, name='signupPage'),
    path('home/', views.homePage, name='homePage'),
    path('logout/', views.logoutPage, name='logoutPage'),
]

Story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AuthSystem.urls')),
]

AuthSystem/models.py
from django.db import models

# Create your models here.

AuthSystem/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, models
from django.contrib.auth.models import User
from django.db import IntegrityError

# Create your views here.
def loginPage(request):
    if request.method == "POST":
        loginUsername = request.POST['loginName']
        loginPassword = request.POST['loginPass']
        user = authenticate(request, username=loginUsername, password=loginPassword)

        if user is not None:
            login(request, user)
            return redirect('home/')

    return render(request, 'loginPage.html')

def signupPage(request):
    if request.method == "POST":
        signupUsername = request.POST['signupName']
        signupEmail = request.POST['signupEmail']
        signupPassword = request.POST['signupPass']

        try:
            user = User.objects.create_user(username=signupUsername, password=signupPassword, email=signupEmail)
        except IntegrityError:
            return render(request, 'signupPage.html')
        
        user.save()
        return redirect('/')

    return render(request, 'signupPage.html')

def homePage(request):
    return render(request, 'homePage.html')

def logoutPage(request):
    if request.method == "POST":
        if request.POST['logout'] == 'Yes':
            logout(request)
            return redirect('/')
        elif request.POST['logout'] == 'No':
            return render(request, 'homePage.html')
    
    return render(request, 'logoutPage.html')

AuthSystem/templates/homePage.html
<!DOCTYPE html>
{% load static %}
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    </head>

    <body>
        <h1>Welcome to Home Page</h1>
        <h2>hello {{user}}</h2>
        <button class="btn btn-outline-primary"><a href="{% url 'AuthSystem:logoutPage' %}">Log Out</a></button>
   </body>
</html>

AuthSystem/templates/loginPage.html
<!DOCTYPE html>
{% load static %}
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    </head>

    <body>
        <h1>Welcome to Login Page</h1>
        <h2>Log In</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="loginName">Username</label>
                <input type="text" class="form-control" name="loginName" id="loginName" placeholder="Enter username">
            </div>
            <div class="form-group">
                <label for="loginPass">Password</label>
                <input type="password" class="form-control" name="loginPass" id="loginPass" placeholder="Enter password">
            </div>
            <button type="submit" class="btn btn-primary">Log In</button>
        </form>
        <div style="display:flex">
            <p>Not signed up yet? Click&nbsp;</p>
            <a href="{% url 'AuthSystem:signupPage' %}">here</a>
        </div>
   </body>
</html>

AuthSystem/templates/logoutPage.html
<!DOCTYPE html>
{% load static %}
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    </head>

    <body>
        <h1>Log Out</h1>
        <h2>hello {{user}}</h2>
        <p>Are you sure?</p>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <input type="submit" value="Yes" class="form-control" name="logout">
            </div>
            <div class="form-group">
                <input type="submit" value="No" class="form-control" name="logout">
            </div>
        </form>
   </body>
</html>

AuthSystem/templates/signupPage.html
<!DOCTYPE html>
{% load static %}
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}"> -->
    </head>

    <body>
        <h1>Sign Up</h1>
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="signupName">Username</label>
                <input type="text" class="form-control" name="signupName" id="signupName" placeholder="Enter username">
            </div>
            <div class="form-group">
                <label for="signupEmail">Email</label>
                <input type="email" class="form-control" name="signupEmail" id="signupEmail" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="signupPass">Password</label>
                <input type="password" class="form-control" name="signupPass" id="signupPass" placeholder="Enter password">
            </div>
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
   </body>
</html>